apiVersion : apps/v1
kind: Deployment
metadata:
  name: containeraz 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containeraz
  template:
    metadata:
      labels:
        app: containeraz 
    spec:
      containers:
        - name: containeraz 
          image: containeraz1.azurecr.io/containeraz
          ports:
          - containerPort: 8080