apiVersion : apps/v1
kind: Deployment
metadata:
  name: myappc 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myappc
  template:
    metadata:
      labels:
        app: myappc 
    spec:
      containers:
        - name: myappc 
          image: containeraz1.azurecr.io/myappc
          ports:
          - containerPort: 8080